[package]
name = "aero-rs"
description = "A rewrite of Campbell Aero in Rust, with a pluggable architecture"
publish = false
version = "0.1.0"

edition = "2021"

[dependencies]
ads1x1x = "0.2.2"
anyhow = { version = "1.0.77", features = ["backtrace"] }
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.12", features = ["derive", "env"] }
flexi_logger = "0.27.3"
log = "0.4.20"
paste = "1.0.14"
rppal = { version = "0.17.1", features = ["hal"] }
serde = { version = "1.0.193", features = ["derive"] }
serde-constant = "0.1.0"
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["full"] }
